# top level stuff you probably don't need to touch
# highlighter: pygments
# markdown: rdiscount
# rdiscount:
#   extensions: [smart]
markdown: kramdown
highlighter: rouge
# permalink: /:title.html
paginate: 5
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-feed
# port: 3000
# safe: true

# pages:
  # - '/about'
  # - '/cv'

# edit here to achieve your personal greatness
url: "http://www.saraemoore.com/"
baseurl: ""
title: Sara E. Moore
author: Sara Moore
name: Sara Moore
description: Personal website of Sara Moore, Biostatistics PhD candidate at UC Berkeley.
#avatar: http://files.saraemoore.com/images/sara_wjwed_zoom_square.png
avatar: http://files.saraemoore.com/images/genentech_small.png
avatar_small: http://files.saraemoore.com/images/sara_saturn_cafe_square.png
email: sara@saraemoore.com
email_full: mailto:sara@saraemoore.com
website: www.saraemoore.com
website_full: http://www.saraemoore.com
github: saraemoore
twitter: sara_e_moore
linkedin: saraemoore
# stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
google_analytics: UA-48006600-4

tel: 919 627 7272
tel_full: tel:+19196277272
google_maps: 'https://www.google.com/maps/place/Haviland+Hall,+Berkeley,+CA+94709'
address: 101 Haviland Hall,<br />MC 7358
postcode: 94720-7358
city: Berkeley
state: California
country: United States

# hilitecolor: "#27A822"
# hilitecolor: "#eb6e1f"
hilitecolor: "#008080"
# tagcolor: "#1f9ceb"
tagcolor: "#e84e23"

# needed for travis-ci build
exclude: [vendor]
